export { default as HeroSection } from './HeroSection'
export { default as PainPointsSection } from './PainPointsSection'
export { default as ValuePropsSection } from './ValuePropsSection'
export { default as HowItWorksSection } from './HowItWorksSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as PopularGuidesSection } from './PopularGuidesSection'
export { default as CTASection } from './CTASection'
export { default as FooterSection } from './FooterSection'
